CREATE TABLE IF NOT EXISTS socis (
    numero_soci INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    nom VARCHAR(100) NOT NULL,
    cognom VARCHAR(100) NOT NULL,
    dni VARCHAR(25) NOT NULL,
    federat INTEGER(1) NOT NULL
);